### ISSUE TITLE
update s3 build

### ISSUE THREAD

**Issue by jschoch** [jschoch/espELSfrontend#3]
@digiexchris   tracking this here.

**Comment by jschoch** [comment]
likely need to think about releases and version compatability...

**Comment by digiexchris** [comment]
yup, agreed. Do you have any indication of if there are other users?

**Comment by jschoch** [comment]
nope, but if there are other users I'm sure they will raise hell when everything starts changing!

**Comment by jschoch** [comment]
So i'm thinking something like this:

```
UI connects to controler, 
   sends hello or ping along with version parameter. 
        cmd: "hello", vsn: "0.0.2"
controller checks to see if an active connection exists,  
    if not replies with cmd: "vsn_fail", 
    if the vsn passes it sends the configuration

```

I will need to start tagging releases and ensuring a working build is linked to the readme with a link to a working UI.

**Comment by digiexchris** [comment]
I like it! And this kind of thing will build people's confidence in trying
it out
