### ISSUE TITLE
Text box for defined amount of movement via the virtual encoder

### ISSUE THREAD

**Issue by digiexchris** [jschoch/espELSfrontend#4]
For hardware debugging and error measurement purposes, it would be handy to ask the virtual encoder to move the stepper by a defined number of units (wether distance, rotations, almost doesn't matter). I'd like to be able to measure error using my touchdro because I have a weird leadscrew pitch that is likely going to cause some error in almost any configuration.

**Comment by jschoch** [comment]
thanks for moving this,  wondering if you use discord, I hang out in the breakingTaps server (an interesting place) https://discord.gg/R45uCXcEv4  may save us on some back and forth in issues.

**Comment by jschoch** [comment]
this should be in the "renaming" (maybe the dev) branch, give it a try
